/* optrs - generated by cbindgen. Do not edit by hand. */

#ifndef OPTRS_H
#define OPTRS_H

/* Regenerate with: cargo build -p optrs-cabi */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define OPT_ABI_VERSION 1

enum opt_kind_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
    OPT_KIND_T_CALL = 0,
    OPT_KIND_T_PUT = 1,
};
#ifndef __cplusplus
typedef int32_t opt_kind_t;
#endif // __cplusplus

enum opt_status_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
    OPT_STATUS_T_OK = 0,
    OPT_STATUS_T_DOMAIN = 1,
    OPT_STATUS_T_NO_SOLUTION = 2,
    OPT_STATUS_T_UNSUPPORTED = 3,
    OPT_STATUS_T_NOT_CONVERGED = 4,
    OPT_STATUS_T_NULL_POINTER = 5,
    OPT_STATUS_T_BAD_SIZE = 6,
    OPT_STATUS_T_BUFFER_TOO_SMALL = 7,
    OPT_STATUS_T_PANIC = 8,
};
#ifndef __cplusplus
typedef int32_t opt_status_t;
#endif // __cplusplus

enum opt_style_t
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
    OPT_STYLE_T_EUROPEAN = 0,
    OPT_STYLE_T_AMERICAN = 1,
    OPT_STYLE_T_BERMUDAN = 2,
};
#ifndef __cplusplus
typedef int32_t opt_style_t;
#endif // __cplusplus

typedef struct opt_pricer_t opt_pricer_t;

/**
 * Option specification. `dates`/`n_dates` are read only when
 * `style == OPT_STYLE_BERMUDAN` and may be null otherwise.
 */
typedef struct {
    uint32_t size;
    opt_kind_t kind;
    opt_style_t style;
    uint32_t _pad;
    double spot;
    double strike;
    double rate;
    double div_yield;
    double vol;
    double time;
    const double *dates;
    uintptr_t n_dates;
} opt_option_t;

/**
 * Pricing output. `has_greeks` and `has_std_error` tell the caller which
 * optional fields were actually populated.
 */
typedef struct {
    uint32_t size;
    int32_t engine;
    int32_t has_std_error;
    int32_t has_greeks;
    double price;
    double std_error;
    double delta;
    double gamma;
    double vega;
    double theta;
    double rho;
    /**
     * Refinements used by `opt_price_converged`; 0 otherwise.
     */
    uint32_t refinements;
    /**
     * Non-zero when Richardson extrapolation was applied.
     */
    int32_t extrapolated;
} opt_result_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Semantic version of the library as a NUL-terminated static string.
 */
const char *opt_version(void);

/**
 * ABI version. Bump only on a breaking layout change. Callers should compare
 * this against the value they compiled against and refuse to run on mismatch.
 */
uint32_t opt_abi_version(void);

/**
 * Byte size of `opt_option_t` as this build sees it. Lets a binding verify
 * struct layout agreement at load time instead of corrupting memory later.
 */
uintptr_t opt_sizeof_option(void);

uintptr_t opt_sizeof_result(void);

/**
 * Message for the most recent failure on this thread, or NULL if none.
 * Valid until the next optrs call on this thread. Copy it if you need to keep it.
 */
const char *opt_last_error_message(void);

void opt_clear_error(void);

/**
 * Create a pricer with default configuration. Returns NULL only on allocation
 * failure. Free with `opt_pricer_free`.
 */
opt_pricer_t *opt_pricer_new(void);

/**
 * Free a pricer. Safe to call with NULL. Double-free is undefined.
 *
 * # Safety
 * `p` must be NULL or a pointer from `opt_pricer_new` not yet freed.
 */
void opt_pricer_free(opt_pricer_t *p);

/**
 * Toggle flags take int for C89-friendliness; non-zero means true.
 *
 * # Safety
 * `p` must be a live handle.
 */
opt_status_t opt_set_mc_antithetic(opt_pricer_t *p, int32_t on);

/**
 * # Safety
 * `p` must be a live handle.
 */
opt_status_t opt_set_mc_control_variate(opt_pricer_t *p, int32_t on);

/**
 * # Safety
 * `p` must be a live handle.
 */
opt_status_t opt_set_richardson(opt_pricer_t *p, int32_t on);

/**
 * Restore every knob to its default.
 *
 * # Safety
 * `p` must be a live handle.
 */
opt_status_t opt_pricer_reset(opt_pricer_t *p);

/**
 * Human-readable engine name, or NULL for an unknown id.
 */
const char *opt_engine_name(int32_t engine);

/**
 * Number of engines. Ids are contiguous in `[0, opt_engine_count())`.
 */
int32_t opt_engine_count(void);

/**
 * Writes 1 into `*out` when the engine can price this option, 0 otherwise.
 *
 * # Safety
 * `option` and `out` must be valid pointers; see `OptOption::to_request`.
 */
opt_status_t opt_engine_supports(int32_t engine,
                                 const opt_option_t *option,
                                 int32_t *out);

/**
 * Price with an explicit engine at the configured discretisation.
 *
 * # Safety
 * All pointers must be valid; `out->size` must be set by the caller.
 */
opt_status_t opt_price(const opt_pricer_t *p,
                       int32_t engine,
                       const opt_option_t *option,
                       opt_result_t *out);

/**
 * Price with the cheapest engine supporting the option.
 *
 * # Safety
 * As `opt_price`.
 */
opt_status_t opt_price_auto(const opt_pricer_t *p,
                            const opt_option_t *option,
                            opt_result_t *out);

/**
 * Refine the discretisation until successive prices agree within tolerance.
 *
 * # Safety
 * As `opt_price`.
 */
opt_status_t opt_price_converged(const opt_pricer_t *p,
                                 int32_t engine,
                                 const opt_option_t *option,
                                 opt_result_t *out);

/**
 * Full greeks. Always sets `has_greeks`.
 *
 * # Safety
 * As `opt_price`.
 */
opt_status_t opt_greeks(const opt_pricer_t *p,
                        int32_t engine,
                        const opt_option_t *option,
                        opt_result_t *out);

/**
 * Price under every supporting engine. Writes up to `capacity` entries into
 * `results` and the actual count into `*n_written`. Pass a capacity of
 * `opt_engine_count()` to be safe. Each entry must have `size` pre-set.
 *
 * Individual engine failures are not fatal: the entry is written with
 * `engine = -1` and skipped, so one bad engine does not lose the others.
 *
 * # Safety
 * `results` must point to `capacity` writable `opt_result_t`.
 */
opt_status_t opt_price_all(const opt_pricer_t *p,
                           const opt_option_t *option,
                           opt_result_t *results,
                           uintptr_t capacity,
                           uintptr_t *n_written);

/**
 * Black-Scholes implied volatility from a European price.
 *
 * # Safety
 * `option` and `out` must be valid. `option->vol` is ignored.
 */
opt_status_t opt_implied_vol(const opt_option_t *option,
                             double target_price,
                             double *out);

/**
 * Convenience for bindings: fill an option struct with correct `size` and
 * zeroed optional fields, so callers never forget the size handshake.
 *
 * # Safety
 * `out` must point to a writable `opt_option_t`.
 */
opt_status_t opt_option_init(opt_option_t *out);

/**
 * # Safety
 * `out` must point to a writable `opt_result_t`.
 */
opt_status_t opt_result_init(opt_result_t *out);

/**
 * Unused today, but exported so bindings can link against a stable free
 * function if a future call returns heap strings.
 *
 * # Safety
 * `s` must be NULL or a pointer this library allocated.
 */
void opt_string_free(char *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* OPTRS_H */
