# crates/optrs-engine/Cargo.toml
[package]
name = "optrs-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
optrs-core.workspace = true
optrs-cos.workspace = true
optrs-tree.workspace = true
optrs-fd.workspace = true
optrs-mc.workspace = true

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "engines"
harness = false
